version: "3.7"
services:

  app:
    build:
      args:
        user: ixdf_dev
        uid: 1000
      context: ./
      dockerfile: ./docker-compose/Dockerfile
    image: course-platform
    container_name: course-platform-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - course-platform-network

  db:
    image: mysql:5.7
    container_name: course-platform-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    networks:
      - course-platform-network

  db-tests:
    image: mysql:5.7
    container_name: course-platform-db-tests
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./.docker/mysql-tests:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - course-platform-network

  nginx:
    image: nginx:alpine
    container_name: course-platform-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
      - .docker/nginx/logs:/var/log/nginx
      - .docker/nginx/cache:/var/cache/nginx
      - .docker/nginx/run:/var/run
    networks:
      - course-platform-network

networks:
  course-platform-network:
    driver: bridge
